spring.application.name=security1

#spring.security.user.name=user_01
#spring.security.user.password=root_user
#once we write usename and password here the application won't generate it in console

#to stop other malecious site access our server data via session id saved in cookies
server.servlet.session.cookie.same-site=strict

#other way to stop these malecious access is by making our application stateless
#all rest apis are stateless in real world
#statefull apps - it is able to recall the users authenticated earlier
#stateless apps - it forgets the previous user authentications and consider it new user everytime 

#if we make the application stateless then this CSRF won't be needed

#to disturb default behaviour of this spring security and make stateless and include multi user authentication
#we will use pre-defines classes and beans in spring security and customize them as per our need
#see config class


logging.level.org.springframework.security=DEBUG