spring.application.name=_035Actuators


#to enable all endpoints of actuators
management.endpoints.web.exposure.include=*

#to exclue some endpoints 
#we may not want every information to be exposed
management.endpoints.web.exposure.exclude=env,beans


#if you want to gracefully shutdown your application from runtime 
#i.e. you want to shutdown your application by reaching to an endpoint - NOT RECOMMENDED BUT LET'S SEE
management.endpoint.shutdown.enabled=true

#All actuators req were binded to GET req but the 'shutdown' req is binded to POST req

#developers add below property b/c they don't want anyone to shutdown
#management.endpoint.shutdown.access=unrestricted
